# this is main file of project in this file we defines "stages" to run our project
stages:
  load_data:
    cmd: python src/stage_01_load_save.py
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv